### ISSUE TITLE
params NOT WORK

### ISSUE THREAD

**Issue by bbqi** [daguflow/dagu#635]
use script:
```
params: commit=1
tags: fix🐞
steps:
  - name: step1
    command: bash
    script: |
      echo ${commit}
      export
```

output:
```

declare -x "commit="123"
declare -x 1="\"commit=123"
```
params not declare. please check it. thanks

maybe from version 1.13.1 : (bug) Fix params quoting when using quotes on value by @zph in https://github.com/daguflow/dagu/pull/602

just use  `${commit//\"}`, output not include quotes on value.
